<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=shift-jis">
  <title>DivisionByZeroError</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs"><div class="manualnavbar" style="text-align: center;">
 <div class="prev" style="text-align: left; float: left;"><a href="class.assertionerror.html">AssertionError</a></div>
 <div class="next" style="text-align: right; float: right;"><a href="class.parseerror.html">ParseError</a></div>
 <div class="up"><a href="reserved.exceptions.html">定義済みの例外</a></div>
 <div class="home"><a href="index.html">PHP Manual</a></div>
</div><hr /><div id="class.divisionbyzeroerror" class="reference">
 <h1 class="title">DivisionByZeroError</h1>
 
 
 <div class="partintro"><p class="verinfo">(PHP 7)</p>
 

  <div class="section" id="divisionbyzeroerror.intro">
   <h2 class="title">はじめに</h2>
   <p class="para">
    <span class="ooclass"><strong class="classname">DivisionByZeroError</strong></span>
    は、数値をゼロで割ろうとした場合にスローされます。
   </p>
  </div>

 
  <div class="section" id="divisionbyzeroerror.synopsis">
   <h2 class="title">クラス概要</h2>
 

   <div class="classsynopsis">
    <div class="ooclass"></div>
 

    <div class="classsynopsisinfo">
     <span class="ooclass">
      <strong class="classname">DivisionByZeroError</strong>
     </span>

     <span class="ooclass">
      <span class="modifier">extends</span>
      <a href="class.arithmeticerror.html" class="classname">ArithmeticError</a>
     </span>
     {</div>


    <div class="classsynopsisinfo classsynopsisinfo_comment">/* 継承したメソッド */</div>
    <div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="error.getmessage.html" class="methodname">Error::getMessage</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">Throwable</span> <span class="methodname"><a href="error.getprevious.html" class="methodname">Error::getPrevious</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">mixed</span> <span class="methodname"><a href="error.getcode.html" class="methodname">Error::getCode</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="error.getfile.html" class="methodname">Error::getFile</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">int</span> <span class="methodname"><a href="error.getline.html" class="methodname">Error::getLine</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">array</span> <span class="methodname"><a href="error.gettrace.html" class="methodname">Error::getTrace</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="error.gettraceasstring.html" class="methodname">Error::getTraceAsString</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">public</span> <span class="type">string</span>  <span class="methodname"><a href="error.tostring.html" class="methodname">Error::__toString</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">private</span> <span class="type">void</span> <span class="methodname"><a href="error.clone.html" class="methodname">Error::__clone</a></span>
    ( <span class="methodparam">void</span>
   )</div>

   }</div>
 

 
  </div>
 </div>
</div>
<div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="118928""></a>
  <div class="note">
   <strong class="user">salsi at icosaedro dot it</strong>
   <a href="#118928" class="date">01-Mar-2016 02:27</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Note that on division by zero 1/0 and module by zero 1%0 an E_WARNING is triggered first (probably for backward compatibility with PHP5), then the DivisionByZeroError exception is thrown next.<br />
<br />
The result is, for example, that if you set the maximum level of error detection with error_level(-1) and you also map errors to exception, say ErrorException, then on division by zero only this latter exception is thrown reporting "Division by zero". The result is that a code like this:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="comment">// Set a safe environment:<br />
</span><span class="default">error_reporting</span><span class="keyword">(-</span><span class="default">1</span><span class="keyword">);<br />
<br />
</span><span class="comment">// Maps errors to ErrorException.<br />
</span><span class="keyword">function </span><span class="default">my_error_handler</span><span class="keyword">(</span><span class="default">$errno</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">)<br />
{ throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">); }<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="default">1</span><span class="keyword">/</span><span class="default">0</span><span class="keyword">;<br />
}<br />
catch(</span><span class="default">ErrorException $e</span><span class="keyword">){<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"got </span><span class="default">$e</span><span class="string">"</span><span class="keyword">;<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
allows to detect such error in the same way under PHP5 and PHP7, although the DivisionByZeroError exception is masked off by ErrorException.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="118486""></a>
  <div class="note">
   <strong class="user">Manjunath</strong>
   <a href="#118486" class="date">14-Dec-2015 07:15</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">MathOperation </span><span class="keyword">extends </span><span class="default">Error<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; protected </span><span class="default">$n </span><span class="keyword">= </span><span class="default">10</span><span class="keyword">;<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// Try to get the Division by Zero error object and display as Exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">doArithmeticOperation</span><span class="keyword">(): </span><span class="default">string<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">{<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$value </span><span class="keyword">= </span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">n </span><span class="keyword">% </span><span class="default">0</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } catch (</span><span class="default">DivisionByZeroError $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
</span><span class="default">$mathOperationObj </span><span class="keyword">= new </span><span class="default">MathOperation</span><span class="keyword">();<br />
echo </span><span class="default">$mathOperationObj</span><span class="keyword">-&gt;</span><span class="default">doArithmeticOperation</span><span class="keyword">();</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
<hr /><div class="manualnavbar" style="text-align: center;">
 <div class="prev" style="text-align: left; float: left;"><a href="class.assertionerror.html">AssertionError</a></div>
 <div class="next" style="text-align: right; float: right;"><a href="class.parseerror.html">ParseError</a></div>
 <div class="up"><a href="reserved.exceptions.html">定義済みの例外</a></div>
 <div class="home"><a href="index.html">PHP Manual</a></div>
</div></body></html>
